### ISSUE TITLE
Front-End: proxy calls should be usable for Whisper (-> abstraction)

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#119]
# Task
## Detailed Description

- Enable the frontend to connect to the proxy.
- The communication is limited to the exact specification of whisper.
## Associated story
#117 Play off-chain-chess without validation
## Notes

Compare with #118 and #120

**Comment by graup** [comment]
- Will add a `move` function to gamesFactory

**Comment by graup** [comment]
API abstraction Implemented in https://github.com/ise-ethereum/web3-shh-dropin-for-proxy
