### ISSUE TITLE
Send and show moves

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#121]
# Task
## Detailed Description

- The frontend communicats with the proxy to send moves.
- it displays moves that have been received via the proxy.
## Associated story

Story: #117 Play off-chain-chess without validation
## Notes

depends on #119 and #118
- [x] Factory function to sign and send moves
- [ ] Call function from game

**Comment by graup** [comment]
https://github.com/ise-ethereum/on-chain-chess/commits/feature/shh
