### ISSUE TITLE
Validate and acknowledge received moves

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#122]
# Story
## User story

As a user, I want to be able to prove, that i have received certain a turn from my opponent to the contract.
## Tasks
#123 Find out how to do signing ([with Mist] + ether accounts)
#124 Validate move/new state and send ACK
#125 Sign new state and move - FEN-to-0x88
#126 Validate signatures
#205 Refactor chess.js to gameFactory
## Notes

Does not contain exeption handling.

**Comment by kyroy** [comment]
Added #205 Refactor chess.js to gameFactory
