### ISSUE TITLE
Find out how to do signing ([with Mist] + ether accounts)

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#123]
# Task
## Detailed Description

- ?
## Associated story

Story: #122  Validate and acknowledge received moves

**Comment by kyroy** [comment]
# Links
- Signing with web3: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsign
- Verify (ecrecover): https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/index.md#ecrecover
- [Verify in client (without ecrecover): http://ethereum.stackexchange.com/a/1794]

**Comment by kyroy** [comment]
I will implement helpers that can be called in the GUI ;)
