### ISSUE TITLE
Find out how to validate signatures in BC

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#128]
# Task
## Detailed Description

- ?
## Associated story

Story: #127 Claim checkmate, stalemate and surrender and submit to BC/claim ether

**Comment by kyroy** [comment]
# Links
- Snippet using ecrevocer: http://ethereum.stackexchange.com/a/718
- (Possible verification snippet for contract: https://gist.github.com/axic/5b33912c6f61ae6fd96d6c4a47afde6d )

**Comment by kyroy** [comment]
I will implement a helper function in the contract ;)
