### ISSUE TITLE
Claim win etc. (Test)

### ISSUE THREAD

**Issue by lisasi** [ise-ethereum/on-chain-chess#130]
# Task
## Detailed Description

- test if claiming a win works as intended, when playing off chain. 
- claimWin, offerDraw, claimTimeout contract functions have to work
## Associated story

Story: #127 Claim checkmate, stalemate and surrender and submit to BC/claim ether
## Notes

depends on #129

**Comment by Peterschuellermann** [comment]
blocked by double ether withdraw bug
