### ISSUE TITLE
Frontend features to draw a game

### ISSUE THREAD

**Issue by kyroy** [ise-ethereum/on-chain-chess#141]
# Task

Frontend features:
- Any player can suggest a draw if it is his turn
- The other player is informed about the wish for a draw
- He can then accept or reject the wish for a draw
- His decision is shown to the first player
- If the game is drawn, the ether is transferred back to both players (after the frontend requested it)
## Associated story

Story: #93

**Comment by dennis-westphal** [comment]
FYI: The claim ether part is already implemented in features/play-for-ether-frontend-additions for #115
