### ISSUE TITLE
Frontend open games not shown on reload

### ISSUE THREAD

**Issue by kyroy** [ise-ethereum/on-chain-chess#143]
# Bug Report
## Expected Behavior

All open games should be shown to join
## Actual Behavior

- Start game under Chrome
- If Firefox is open, game will be shown
- After reload, no game is shown to join

**Comment by dennis-westphal** [comment]
Fixed in https://github.com/ise-ethereum/on-chain-chess/commit/a4491ea2d3a604882615209987a7b55777efbf36
