### ISSUE TITLE
When initializing a new game, double of the ether bet is removed from the players account

### ISSUE THREAD

**Issue by dennis-westphal** [ise-ethereum/on-chain-chess#148]
# Bug Report
## Expected Behavior
- Account balance should be reduced by ether bet
## Actual Behavior
- Account balance is reduced by double ether bet
## Possible Fix
- Transfer half of the ether bet (but this is **very** hacky)
## Steps to Reproduce

1. Go to start game page
2. Note current account balance
3. Start a game with ether bet
4. Compare account balance
## Your Environment
- Firefox
## Notes
- This worked before according to @Kyroy, so it is likely due to one of the more recent pull requests - maybe a bug in Solidity when accepting ether and calling super or so?
## HeavyPanda

Confirmed the bug. Cant find any way the function gets excecuted 2 times. 
## debugging in the gui

searching for:
- Chess.initGame($scope.username, $scope.startcolor .... only one instance
- value: web3.toWei($scope.etherbet, 'ether') .... only one instance
  Also printing the bet return the right value inside the initGame function:
  -console.log('etherbet', $scope.etherbet);
  It also gets transformed in the right way so no problem there.
  -console.log('ether converted',web3.toWei($scope.etherbet, 'ether'))
  Searching the internet if its a common problem with the testrpc doesn’t give a solution
## debugging in the chess. sol
- commenting out lines in the     function initGame(string player1Alias, bool playAsWhite) public returns (bytes32) {
  function
  ---> doubling of ther orrurs when 
      gameStates[gameId].setupState(nextPlayerColor); is not commented out
  ---> the first time we use the Gamelogic Library
  ---> even when the call to the Library does nothing the doubling happens
## solution

We need to use the Library. Maybe this is a bug in solidity librarys itself

**Comment by Peterschuellermann** [comment]
The proposed hacky fix is not viable. Although 2x is taken for creation of a game, only 1x is returned when the game is cancelled.

**Comment by dennis-westphal** [comment]
When you only transfer "half" of the ether bet, the correct (full) amount is transferred instead, and when the game is cancelled, the full amount is returned too; so although it is very hacky, it is also very much of a possible solution till we find the root cause to this problem
