### ISSUE TITLE
Setup services and environments

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#16]
# Task 

## Detailed Description

- Set up Jenkins
- Give Intro to Jenkins #12 
- Set up all IDEs 

## Associated story
Story: #10 Every developer is able to work on their own

**Comment by Kyroy** [comment]
What do you mean with "Ide setup"?

**Comment by Kyroy** [comment]
TODO: Write wiki page with basic usage description for a developer

**Comment by Kyroy** [comment]
https://github.com/ise-ethereum/on-chain-chess/wiki/Jenkins
