### ISSUE TITLE
Create overview of ideas for Poker for the presentation

### ISSUE THREAD

**Issue by dennis-westphal** [ise-ethereum/on-chain-chess#172]
# Task
## Detailed Description

- We want to have an overview of how poker can work in the presentation
- This does not have to contain implementation
## Associated story

Story: #157 Presentation

**Comment by graup** [comment]
@Kyroy Machen wir das? Können ja mit Christian besprechen und dann aufschreiben

**Comment by kyroy** [comment]
@graup Jo klar :)
