### ISSUE TITLE
send moves to blockchain, if p2p communication fails

### ISSUE THREAD

**Issue by Peterschuellermann** [ise-ethereum/on-chain-chess#185]
# Task
## Detailed Description

- When a player sends a move based on the blockchain state (and not the signed state received from the other player), and the p2p comm. fails, send move to blockchain (instead of state + move)
## Associated story

Story: #167

**Comment by kyroy** [comment]
This is an extreme error case, we don't need to implement this.

If opponent uses claimTimeout, we get informed about not send move and can respond to blockchain accordingly.
