### ISSUE TITLE
The contract updates and pushes new states

### ISSUE THREAD

**Issue by Peterschuellermann** [ise-ethereum/on-chain-chess#188]
# Task
## Detailed Description

- the contract saves and pushes received states if they are valid and newer than the previously persisted state
## Associated story

Story: #167

**Comment by Tin-App** [comment]
The BC already saves states when they are newer than the current state & valid with the moveFromState() in Chess.sol. The "pushing" part is done by execution of the move() function inside the moveFromState() function. Causing an GameStateChanged() event.

**Comment by Tin-App** [comment]
Is this task about implementing a changeGameState() without a move?

**Comment by graup** [comment]
I am under the impression that this task is already implemented.
