### ISSUE TITLE
Contract Architektur (On und Off chain)

### ISSUE THREAD

**Issue by Peterschuellermann** [ise-ethereum/on-chain-chess#195]
# Task
## Detailed Description

- Zeige anhand eines Diagramms (welches erstellt werden muss) wie die Architektur des Contracts aufgebaut ist. Differenziere dabei zwischen On und Off chain Varianten des Contracts.
  - Die Kommunikation zwischen front und backend ist Teil dieses Tickets, nicht von Ticket #196
## Associated story

Story: #157

**Comment by graup** [comment]
@Pepperrs @dennis-westphal @HeavyPanda  ich würde ein Diagram zur Endgame-Kommunikation machen, teil dieses Tasks oder eines anderen?

**Comment by Peterschuellermann** [comment]
Ist Teil von #196 @graup

**Comment by graup** [comment]
Hat aber eigentlich nicht direkt was mit Frontend zu tun, das gleiche gilt ja auch für off-chain. Ich meine sowas: https://raw.githubusercontent.com/wiki/ise-ethereum/on-chain-chess/images/endgame.png

**Comment by Peterschuellermann** [comment]
Da es was mit beiden Themen zu tun hat, wir es aber nicht in beiden Tickets drin haben können, liegt es unter #196

**Comment by Peterschuellermann** [comment]
Hmm, OK, ich weiß jetzt was Du meinst, @graup . Wenn @dennis-westphal nichts dagegen hat, können wir den Kommunikationsteil der Aufgabe unter dieses Ticket fassen. (?)

**Comment by dennis-westphal** [comment]
Klar, kannst du gerne machen.
