### ISSUE TITLE
The user can join an initialized game of chess

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#20]
# Story 

## User story

As a user, I want to be able to join a game of chess with a game ID i know.

## Tasks
- #32 Create an HTML page to join a game
- #45 Create backend method to join a game

## Acceptance criteria

- [x] When joining a game, the user must enter his or her name
- [x] When joining a game, the user can see the name of his or her enemy

**Comment by Kyroy** [comment]
The features have to be tested with different accounts, interacting with each other.
