### ISSUE TITLE
offer draw fails and breaks the game

### ISSUE THREAD

**Issue by Peterschuellermann** [ise-ethereum/on-chain-chess#209]
# Bug Report
## Context

When a player offers a draw, the game freezes
## Expected Behavior

when a draw is offered the game provides an option for the other player to accept the draw
## Actual Behavior

when a player offers a draw the game breaks, for off-chain it freezes and a reload displays the board without pieces, for on chain the board freezes and the next move is not transmitted to the player. In the on chain version, the reload doesnt change anything.
## Steps to Reproduce

1. start game
2. (connect to off chain)
3. after any number of turns offer draw
4. game breaks
## Your Environment

- Version used: Latest commit fafd26d
- Environment name and version (e.g. Chrome 39, node.js 5.4): chromium 51 and Firefox 47
- Operating System and version (desktop or mobile): Linux
- Link to your project:

**Comment by graup** [comment]
Thank you, but the version you mentioned is known to be broken in many ways. As discussed, the whole thing is currently being refactored and bugs are fixed here (including the one you mentioned): https://github.com/ise-ethereum/on-chain-chess/pull/206

To help, please continue testing in that branch! :)
