### ISSUE TITLE
The user has an ELO score

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#21]
# Story 

## User story

As a user I want to have an ELO score calculated, so I can compare myself to other players and choose oponents that are on an equal level of mine. Also I want to be able to boast.

## Tasks
- todo

## Acceptance criteria

- [ ] Todo

## Notes

This would allow our issues to be streamlined as their form resembles each other. It would also help in creating issues as the process requires less time.

**Comment by graup** [comment]
Score is now updated. What's missing is some sort of output. Should we add the player's Elo to the game list?
