### ISSUE TITLE
Create an HTML page to start a new game

### ISSUE THREAD

**Issue by dennis-westphal** [ise-ethereum/on-chain-chess#26]
# Task 

## Detailed Description

- HTML page contains an input field for the users name
- Selector (graphical or select box) to choose a color
- Calls the backend method to start a new game
- Listens to the event response
- Displays error messages from the event response
- Redirects the user to the chess game when the creation of the game was successful (event with game id emitted by #44)

## Associated story
Story: #18 The user can initialize a game of chess

**Comment by graup** [comment]
This probably should also have a Select box to select the (ethereum) account with which the game is initialized. Could just use the default account, but especially for testing (on the same device) this would come in handy.

**Comment by Kyroy** [comment]
@dennis-westphal Redirects the user to the chess game is still nissing
