### ISSUE TITLE
Write contract function that validates chess moves

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#4]
# Task

## Detailed Description

- Write a solidity contract that validates all chess moves for a specific game
- When a move is calculated write its result to the blockchain #49 

## Associated story
Story: #35 

## Notes

We can use the 0x88 [schematic](http://web.archive.org/web/20071026130204/http://www.seanet.com/~brucemo/topics/0x88.htm) for this. 
SubTask:
- Create working prototype
- Concept -> https://github.com/ise-ethereum/on-chain-chess/wiki/Chess-solidity-methods
- it needs a representation to validate -> https://github.com/ise-ethereum/on-chain-chess/wiki/Chess-board-representation

**Comment by graup** [comment]
Done and merged, to be tested #74
