### ISSUE TITLE
Evaluate usability of existing frontend libraries for game or asset representation

### ISSUE THREAD

**Issue by dennis-westphal** [ise-ethereum/on-chain-chess#41]
# Task

## Detailed Description

- Check if libraries can be used and how easily they can be modified
- Check the existing assets in https://github.com/ethereum/dapp-styles
- Report your findings to the wiki

## Associated story
Story: #25 

## Notes

Libraries:
- http://creativejs.com/2012/12/3d-hartwig-chess/

**Comment by Pepperrs** [comment]
looks good.

**Comment by Pepperrs** [comment]
Nothing in the wiki yet.

**Comment by wiilee** [comment]
https://github.com/ise-ethereum/on-chain-chess/wiki/Chess-library
