### ISSUE TITLE
Implement an "End game" / Surrender button

### ISSUE THREAD

**Issue by dennis-westphal** [ise-ethereum/on-chain-chess#42]
# Task

## Detailed Description

- Users can click on a button to surrender
- Send surrender information to backend
  - The contract notes that the game is ended
  - Contract generates GameEnded(gameId, winnerAddress) event (see #49)
- The other player is informed about winning the game (listening to the event as in #40)

## Associated story
Story: #25

**Comment by graup** [comment]
Merged in 0591730cd0b2866fd79dfb0b8dd3631e608383c6
