### ISSUE TITLE
Set up server for static resources

### ISSUE THREAD

**Issue by dennis-westphal** [ise-ethereum/on-chain-chess#46]
# Task 

## Detailed Description

- Set up a server that can be accessed using SFTP
- Serves static resources only
- Setup jenkins Jenkins to deploy to static server

## Associated story
Story: #18 The user can initialize a game of chess

**Comment by Kyroy** [comment]
Server is mostly set up. Jenkins is able to deploy to the directory (I just need to add the command to the build process).
BUT: It makes no sense to build the static files and deploy it to a server, because we are using the testrpc. So everyone has a different contract id and so on...
We may want to ask this at the next meeting with ethereum ;) (@graup)

@dennis-westphal @Pepperrs

**Comment by Kyroy** [comment]
So we may want to create our own test network? Then we can easily test our Dapp with different people ;)

https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster

@graup

**Comment by Kyroy** [comment]
https://souptacular.gitbooks.io/ethereum-tutorials-and-tips-by-hudson/content/private-chain.html#set-up-static-nodes

**Comment by graup** [comment]
I think this is a good idea.

**Comment by Kyroy** [comment]
I set up the node on our server. It is actually not mining. Don't know if we want this.
Documentation wiki: [Ethereum-Testnet](https://github.com/ise-ethereum/on-chain-chess/wiki/Ethereum-Testnet)

**Comment by dennis-westphal** [comment]
I don't pay for electricity... so go for it :D

**Comment by Kyroy** [comment]
@dennis-westphal Mining on our Testnet is not that expensive because the problem to solve is very easy.

@graup thx

**Comment by Kyroy** [comment]
@graup We may also just use ```geth --testnet --rpc```. I think this is a fully working blockchain, isn't it?

**Comment by graup** [comment]
@Kyroy Yes but you can't connect from outside to it, kind of defeating the purpose of serving the site.

**Comment by Kyroy** [comment]
Are you sure you cannot connect? I started it and it was syncing blocks. I assumed it is a global testnet

**Comment by graup** [comment]
Ah I see, sorry I was confused. If we can easily mine some ETH on there, then yes that sounds like a good idea!

**Comment by Kyroy** [comment]
Documentation can be found here: https://github.com/ise-ethereum/on-chain-chess/wiki/Ethereum-Testnet  
still under construction
