### ISSUE TITLE
Backend verifies check mate

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#49]
# Task
Contract verifies check mate, a position in which one player's king is in check and has no valid moves left.

## Detailed Description

- Implement `checkForCheckmate` contract function that checks if this condition is indeed the case
  - Contract sets winner
  - Contract generates `GameEnded(gameId, winnerAddress)` event

## Associated story
Story: #53

**Comment by graup** [comment]
Games shouldn't end automatically after a move. As discussed, there should be `checkForCheckmate` and `checkForDraw` functions that the clients call when they have reasonable suspicion that one of them is the case. If these contract functions determine that the game indeed ended, they will then emit `GameEnded` events and could then automatically transfer any betting funds (if we implement that).

**Comment by dennis-westphal** [comment]
When this function is called, the game state is also updated if the validation is successful
