### ISSUE TITLE
Exit npm run test-testrpc after tests

### ISSUE THREAD

**Issue by Kyroy** [ise-ethereum/on-chain-chess#51]
# Bug Report

## Context

It happens that ```npm run test-testrpc``` is running forever and the test will never stop. It is very important for Jenkins that the command exits with the correct code (success / fail) after all tests executed or at least on test failed. (It is not important that it exits immediately if one test fails. It just has to exit!)

## Expected Behavior

```npm run test-testrpc``` should stop after all tests run or stop if one test fail

## Actual Behavior

```npm run test-testrpc``` sometimes keeps running the testrpc client forever

## Steps to Reproduce
http://176.9.247.205:8080/job/on-chain-chess_feature/39/console

## Context

Tests will not stop running or timeout after 5 minutes because this is the current timeout of a Jenkins build.

**Comment by Kyroy** [comment]
@graup @HeavyPanda

**Comment by graup** [comment]
I see. Looks like a problem in the test. This [`done()`](https://github.com/ise-ethereum/on-chain-chess/blob/feature/initGame/test/test.js#L71) is never called and so mocha never exits. Will investigate.

**Comment by graup** [comment]
This could be related to web3 event watchers that are added during the test but not removed. Always watch out to remove these watchers again, otherwise they seem to not get destroyed automatically.

**Comment by Kyroy** [comment]
http://176.9.247.205:8080/job/on-chain-chess_develop_pull-request/10/console

**Comment by Kyroy** [comment]
Again a random test, i looked at: http://176.9.247.205:8080/job/on-chain-chess_feature/115/console

**Comment by kyroy** [comment]
http://176.9.247.205:8080/job/on-chain-chess_feature/141/console  
This bug randomly appears locally, too. After restarting the test, it works.
