### ISSUE TITLE
Save the state of the game in the blockchain

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#58]
# Task

## Detailed Description

- When the game has been initialized, save the state of the game to the blockchain.
- When a move has been performend (and validated), save the state of the game to the blockchain.

## Associated story
Story: #25

**Comment by Pepperrs** [comment]
@graup Ich meine das funktioniert schon. Bist du einverstanden?

**Comment by graup** [comment]
@Pepperrs Ja, das ist in d90a72937bba4e34a9638ed8630126ec24a93f4b schon drin, abgesehen von der Validation natürlich.
