### ISSUE TITLE
Allow movement of chess pieces - Backend

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#59]
# Task

## Detailed Description

- Users can move chess pieces
- When a chess piece exists on the target location, it is beaten and removed
- Movement validation is called. (And handled in #35 )
  - when it passes the move is ok
  - when it does not pass, the move is rejected
- When the move is accepted, save to blockchain (#58 )

## Associated story
Story: #25

**Comment by graup** [comment]
> Beaten chess pieces are removed from the board and their removal is saved in the off-board

why is this necessary? I cannot remember talking about that, it's not in the Python implementation either.
