### ISSUE TITLE
Turn Time

### ISSUE THREAD

**Issue by Pepperrs** [ise-ethereum/on-chain-chess#68]
# Story

## User story

As a user I want to be able to start a game with a limited time per turn.

## Tasks
- Contrals get created in the frontend #177
- Blockchain can handle turntime #180 
- frontend logic gets adapted to turntime #178

## Acceptance criteria

- [ ] The time required can be set to values from 5 minutes to "infinity". 
- [ ] If a Player exceeds their time frame, the player looses

**Comment by kyroy** [comment]
A task of this story is to show the "Claim Timeout" button to the user dynamically (and not only after reload). This was not done in the last Sprint.
