### ISSUE TITLE
Backend verifies stale mate

### ISSUE THREAD

**Issue by graup** [ise-ethereum/on-chain-chess#73]
# Task

Contract checks for stale mate: A position in which a player is not in check, but has no valid moves left.

## Detailed Description

- Implement `checkForStalemate` contract function that checks if this condition is indeed the case
  - Contract sets winner to `0`
  - Contract generates `GameEnded(gameId, 0)` event

## Associated story
Story: #53

**Comment by dennis-westphal** [comment]
When this function is called, the game state is also updated if the validation is successful
