### ISSUE TITLE
Write tests for Contract move validation

### ISSUE THREAD

**Issue by graup** [ise-ethereum/on-chain-chess#74]
# Task

- Add extensive tests to test all move validation cases

## Details

Code should be placed here: https://github.com/ise-ethereum/on-chain-chess/blob/e78f234a44f83a15f95f582b4dbb78bd16bf80ac/test/test_contract.js#L136-L147

## Story
#35

**Comment by kyroy** [comment]
Do we already have some notes for the tests?

**Comment by graup** [comment]
See linked commit on how to write these tests and the Wiki for the board indices. Or what do you mean with notes?

**Comment by kyroy** [comment]
For example existing test cases. @HeavyPanda mentioned he made some tests for the python implementation.

**Comment by graup** [comment]
You can find them here: https://github.com/ise-ethereum/samples/blob/master/test_chess.py

**Comment by kyroy** [comment]
Yes, sure ;) He said something about documenting or writing down his test boards.

**Comment by graup** [comment]
Tests have been written, bugs have been fixed, tests are passing.
Are you planning to write more tests, @Kyroy ? :)

**Comment by kyroy** [comment]
Not quite sure what to test. But I will definitely write at least some pawn promotion tests.
