### ISSUE TITLE
Get game state from contract

### ISSUE THREAD

**Issue by graup** [ise-ethereum/on-chain-chess#79]
# Task

Implement a getter function to retrieve the current game state (board incl flags, players, winner).
## Associated story

Story: #39

**Comment by kyroy** [comment]
In completed, but no pull request?

**Comment by ghost** [comment]
code doesn't work, but is fixed in branch 'feature/chessboard-frontend'.

**Comment by kyroy** [comment]
Tests would be great, too ;)

**Comment by dennis-westphal** [comment]
TODO: Add better documentation for flags to the Wiki (espacially return values)

**Comment by graup** [comment]
Is this still open? We have [these functions](https://github.com/ise-ethereum/on-chain-chess/blob/502acf7fb7ea91104a102e75c26af0b4aa151fa4/contract/Chess.sol#L97-L103) now.

**Comment by kyroy** [comment]
> TODO: Add better documentation for flags to the Wiki (espacially return values)

Still missing

**Comment by graup** [comment]
I see. @lisasi could you do that? :)
