### ISSUE TITLE
Choose Ethereum development tools/libraries

### ISSUE THREAD

**Issue by graup** [ise-ethereum/on-chain-chess#8]
# Task 

## Detailed Description

- Research Ethereum tools
- Decide which tools to use
- Document these tools in the wiki
- Write guides for these tools in the wiki or link good ones there

## Associated story
Story: #10 Every developer is able to work on their own

## Notes
- Wiki: [Technologies used](https://github.com/ise-ethereum/on-chain-chess/wiki/Technologies-used)
- Wiki: [Guide: Development environment](https://github.com/ise-ethereum/on-chain-chess/wiki/Development-environment)

**Comment by graup** [comment]
I started writing this as a little guide here and will continue while we learn more about everything: https://github.com/ise-ethereum/on-chain-chess/wiki/Development-environment

In our project, we are going to use the Webpack approach for now, but it would be easy to switch later.

**Comment by Kyroy** [comment]
@graup I will take a look into the new Visual Studio plugin, maybe this is nice, too ;)

**Comment by Kyroy** [comment]
It is not possible to create a project with existing code....  
In Mix, this is the case, too...  
Just why

**Comment by graup** [comment]
Added another Wiki article as an overview of technologies used in this project: https://github.com/ise-ethereum/on-chain-chess/wiki/Technologies-used
