### ISSUE TITLE
Implement gamesOfPlayers getter function

### ISSUE THREAD

**Issue by graup** [ise-ethereum/on-chain-chess#80]
# Task

Implement a more abstract accessor for gamesOfPlayers (hiding array implementation details)
## Associated story

Story: #39

**Comment by kyroy** [comment]
At the moment, it is not possible to return dynamic arrays (http://ethereum.stackexchange.com/a/3590/1896).  
We are currently doing the proposed workarount: https://github.com/ise-ethereum/on-chain-chess/blob/develop/app/javascript/gamesFactory.js#L251-L260

**Comment by graup** [comment]
@chriseth I think you suggested writing an accessor function, but it seems that we cannot return arrays. Any ideas?

**Comment by chriseth** [comment]
Returning arrays works fine. What is not possible is accessing returned arrays from within solidity.
So you can return arrays to "web3.js" but not to solidity.

**Comment by kyroy** [comment]
@chriseth Do you have a code example for us?

**Comment by chriseth** [comment]
Oh ok, it is not possible to return an array of structs - if that is your problem. But it is possible to return an array of elementary types:

```
contract c {
  uint[] data;
  function getData() returns (uint[]) {
    return data;
  }
}
```

**Comment by kyroy** [comment]
We want to create an array of `bytes32` (game ids), that are stored in a `mapping`. So we have to create a dynamic array in the function and return it.  
I haven't found an example, where i can create an array and return it in a function.

Edit: We know the size of the array, so it must not be dynamic. But the size differs from call to call.

**Comment by chriseth** [comment]
```
contract c {
  function getData(uint length) returns (bytes32[]) {
    bytes32[] memory data = new bytes32[](length);
    data[0] = 1;
    data[1] = 2;
    return data;
  }
}
```

**Comment by kyroy** [comment]
Thanks :)
