### ISSUE TITLE
Implement closePlayerGame contract function

### ISSUE THREAD

**Issue by graup** [ise-ethereum/on-chain-chess#82]
# Task

Let the user "close" a game by removing it from the `gamesOfPlayers[player]` list, but only if the game is not currently running. A game is running if it has two players and no draw/checkmate occurred.
## Associated story

Story: #xx

**Comment by kyroy** [comment]
> no draw/checkmate occurred

How do I check if one of these occured? If `Game.winner` is set? Or is there a special flag in the board representation?

**Comment by graup** [comment]
I think we need a new flag for this, because in case of draw there is no winner.

**Comment by kyroy** [comment]
Is there a documentation of actually used flags in the shadow board?

**Comment by graup** [comment]
https://github.com/ise-ethereum/samples/blob/master/Chess.py#L46

**Comment by graup** [comment]
http://solidity.readthedocs.io/en/latest/structure-of-a-contract.html?highlight=modifier#function-modifiers

**Comment by kyroy** [comment]
Why do we want to remove the game from the `gamesOfPlayers`? Shouldn't a player be able to get all his played games?

**Comment by graup** [comment]
Maybe that could be useful too, but right now we only need that list to display it in the UI as open/running games.
Maybe we should make it two lists? gamesOfPlayers and activeGamesOfPlayers?

**Comment by kyroy** [comment]
The UI has to get local data only. But in the contract we would have to go through the whole activeGamesOfPlayers mapping (stack) to delete a game that finishes. Do we really want to add this?
