### ISSUE TITLE
Transfer ether to winning player

### ISSUE THREAD

**Issue by dennis-westphal** [ise-ethereum/on-chain-chess#91]
# Task
## Detailed Description

- The contract transfers the ether a player has won to his account
## Associated story

Story: #71 Play for ether
## Notes

Missing:
- [ ] ClaimWin should allow the user to claim ether if the game is a draw
- [ ] ClaimWin should allow the user to claim ether if the has never been joined

**Comment by kyroy** [comment]
important! https://blog.ethereum.org/2016/06/10/smart-contract-security/

**Comment by dennis-westphal** [comment]
This is a function that is called by the frontend

**Comment by Peterschuellermann** [comment]
The function has been implemented -  but as @Kyroy has pointed out it neglects draws and games that were never joined by a second party.

**Comment by kyroy** [comment]
von @graup: die zeile ist überflüssig, wird doch eh alles reverted https://github.com/ise-ethereum/on-chain-chess/blob/develop/contract/Chess.sol#L259

**Comment by graup** [comment]
Should this already work? At least it's throwing errors already :)
https://github.com/ise-ethereum/on-chain-chess/issues/151
